### ISSUE TITLE
请问如何增加端口映射？

### ISSUE THREAD

**Issue by xlsw** [linuxeye/bypanel#8]
如题，我需要反向代理本机syncthing的8384端口，但是bypanel的web服务默认只映射了80和443。
我看了docker-compose.yml和..env两个文件，
猜测可能照着添加就行，但是我还是不敢轻举妄动，特来请教！
再次感谢L大的无私奉献！
敬礼！

**Comment by linuxeye** [comment]
如果是nginx代理 8384 端口
`bypanel vhost add`
选择2 向代理地址:  `http://服务器内网IP: 8384` 即可

**Comment by xlsw** [comment]
你说的这一步以及配置了的，但是访问502，后来我意识到应该是没有给nginx镜像配置8384的端口映射。
所以我的意思不是nginx监听端口，是端口映射，不是要把容器的端口映射到宿主机的吗？就像nginx镜像映射了80和443，MySQL映射了3306

**Comment by xlsw** [comment]
是的，我的nginx容器不能访问服务器内网IP:8384
我刚刚想通了，我本来以为是容器端口映射原因，但端口映射是监听来自外部的访问，而不是访问容器外服务的端口。
我查了一下DOCKER默认网络模式是桥接，所以访问不到服务器内网。
那我把syncthing也用容器镜像，nginx就能访问到它了。
请问我自己安装其他容器镜像，会干扰到bypael不？

**Comment by linuxeye** [comment]
在/opt/bypanel/app/syncthing/latest/docker-compose.yml #创建/opt/bypanel/app/syncthing/latest/目录
```
services:
  syncthing:
    image: syncthing镜像地址
    # Always pull docker image
    #pull_policy: always
    restart: always
    hostname: syncthing
    environment:
      - TZ=${TIMEZONE}
    networks:
      - net

networks:
  net:
    name: ${COMPOSE_NETWORK_NAME}
    driver: bridge
```
之后bypanel configure会自动有syncthing 应用 就可以自己应用了，注意/opt/bypanel/docker-compose.yml 文件暂时没有用。

**Comment by xlsw** [comment]
感谢大佬~
我补充了一下端口映射和文件挂载，供大家参考~
syncthing的config配置监听本地127.0.0.1:8384
用nginx反代127.0.0.1:8384即可。

```
services:
  syncthing:
    image: syncthing/syncthing:latest
    pull_policy: always      #每次拉取最新
    restart: always
    hostname: syncthing
    
    environment:
      - PUID=1001      #指定用户ID
      - PGID=1001      #指定组ID
      - TZ=${TIMEZONE}
    
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp      #本地发现端口
    
    networks:
      - net
    
    volumes:
      - ~/syncthing/.config:/var/syncthing/config      #挂载配置文件
      - ~/syncthing:/var/syncthing      #挂载数据路径

networks:
  net:
    name: ${COMPOSE_NETWORK_NAME}
    driver: bridge
```
